
alias: Control AJAX via Relay from Alarmo (Double Check with SIA)
description: >-
  Controls AJAX system via relays (key fob) ONLY when both Alarmo Level 0 and
  Level 1 areas are simultaneously switched to the same state. Also verifies
  state change using SIA feedback to ensure successful switch.
triggers:
  - entity_id:
      - alarm_control_panel.0_level
      - alarm_control_panel.1st_level
    trigger: state
conditions:
  - condition: template ##this condition will check if both areas are the same state
    value_template: |
      {{
        states('alarm_control_panel.0_level') == states('alarm_control_panel.1st_level')
      }}
actions:
  - variables:
      target_state: "{{ states('alarm_control_panel.0_level') }}"
  - choose: ##we use choose operator to choose between 3 possible states - armed_away / disarmed / armed_night
      - conditions:
          - condition: template
            value_template: "{{ target_state == 'armed_away' }}"
        sequence:
          - repeat:
              count: 3 ##repeat sequence 3 times to make sure AJAX Fob noticed button push and sent command to Hub
              sequence:
                - target:
                    entity_id: switch.ajax_space_control_button_relay_switch_2
                  action: switch.turn_on
                  data: {}
                - delay:
                    seconds: 2  ##we already have Momentary/Itching mode Pulse duration configured in TUYA App but lets add 2 second delayed Turn Off action anyway
                - target:
                    entity_id: switch.ajax_space_control_button_relay_switch_2
                  action: switch.turn_off
                  data: {}
                - wait_template: > ##this section will add 10 second timer to verify via SIA Integration that AJAX Hub has indeed changed state to desirable armed_away
                    {{
                    is_state('alarm_control_panel.main_hall_pir_motion_sensor',
                    'armed_away') }}
                  timeout: "00:00:10"
                  continue_on_timeout: true
                - condition: template
                  value_template: >
                    {{
                    is_state('alarm_control_panel.main_hall_pir_motion_sensor',
                    'armed_away') }}
                - stop: AJAX switched successfully to Armed Away. ##Stop operator will prevent sequence repeat if SIA Integration has noticed state change
                - delay:
                    seconds: 3 ##additional delay to prevent quick button presses, prevent cascading failures, loops, Allow AJAX Hub to process and stabilize its state
      - conditions:
          - condition: template
            value_template: "{{ target_state == 'disarmed' }}"
        sequence:
          - repeat:
              count: 3
              sequence:
                - target:
                    entity_id: switch.ajax_space_control_button_relay_switch_4
                  action: switch.turn_on
                  data: {}
                - delay:
                    seconds: 2
                - target:
                    entity_id: switch.ajax_space_control_button_relay_switch_4
                  action: switch.turn_off
                  data: {}
                - wait_template: >
                    {{
                    is_state('alarm_control_panel.main_hall_pir_motion_sensor',
                    'disarmed') }}
                  timeout: "00:00:10"
                  continue_on_timeout: true
                - condition: template
                  value_template: >
                    {{
                    is_state('alarm_control_panel.main_hall_pir_motion_sensor',
                    'disarmed') }}
                - stop: AJAX switched successfully to Disarmed.
                - delay:
                    seconds: 3
      - conditions:
          - condition: template
            value_template: "{{ target_state == 'armed_night' }}"
        sequence:
          - repeat:
              count: 3
              sequence:
                - target:
                    entity_id: switch.ajax_space_control_button_relay_switch_3
                  action: switch.turn_on
                  data: {}
                - delay:
                    seconds: 2
                - target:
                    entity_id: switch.ajax_space_control_button_relay_switch_3
                  action: switch.turn_off
                  data: {}
                - wait_template: >
                    {{
                    is_state('alarm_control_panel.main_hall_pir_motion_sensor',
                    'armed_night') }}
                  timeout: "00:00:10"
                  continue_on_timeout: true
                - condition: template
                  value_template: >
                    {{
                    is_state('alarm_control_panel.main_hall_pir_motion_sensor',
                    'armed_night') }}
                - stop: AJAX switched successfully to Night Mode.
                - delay:
                    seconds: 3
mode: single
